# fly.toml app configuration file generated for portfolio-summer-cherry-1893 on 2025-03-28T22:46:07-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'jhern-portfolio'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
